AWSTemplateFormatVersion: 2010-09-09
Description: Research IT Documentation Website
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName : uoy-researchit-website
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
      Tags:
        - Key: description
          Value: Hosts content for the Research IT website
        - Key: name
          Value: research-it-website-bucket
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebsiteBucket
                - '/*'
  OriginAccessID:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
          CloudFrontOriginAccessIdentityConfig:
            Comment:
              Ref: WebsiteBucket
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution for static s3 website.
        DefaultRootObject: index.html
        Enabled: True
        Origins:
        - DomainName: !GetAtt WebsiteBucket.DomainName
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Join [ '', ["origin-access-identity/cloudfront/", !GetAtt OriginAccessID.Id ]]
        DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            ViewerProtocolPolicy: redirect-to-https
            Compress: True
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
Outputs: 
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt WebsiteBucket.WebsiteURL
  CloudFrontDistributionID:
    Description: ID of the CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.Id
  BucketName:
    Description: Website bucket name
    Value: !Ref WebsiteBucket
