site_name: Research IT
theme: 
  name: material
nav:
  - Home: 'index.md'
  - Viking:
    - 'Quick Start Guide': 'viking/quickstart.md'
    - 'How to log in to Viking': 'viking/login.md'
    - 'Information for grants and acknowledgement': 'viking/acknowledgement.md'
    - 'Case Studies': 'viking/case_studies.md'
  - 'Interactive Research Linux Service':
    - 'Accessing the Servers': 'mlrs/access.md'
    - 'COMSOL Multiphysics': 'mlrs/comsol.md'
    - 'Copying files from another host': 'mlrs/file_transfer.md'
    - 'How many cores is my program using?': 'mlrs/cores.md'
    - 'Using the "screen" command to run multiple programs': 'mlrs/screen.md'
  - 'Regional and National Research Computing Facilities': 'hpc.md'
  - 'Cloud Computing': 'cloud.md'
  - 'Physics compute cluster':
    - 'How to access the physnodes': 'physics/access.md'
    - 'Modules': 'physics/modules.md'
    - 'Submitting jobs': 'physics/submitting.md'
    - 'Job scripts': 'physics/job_scripts.md'
    - 'Simple Matlab, Stata, and Gaussian jobs': 'physics/matlab_stata_gaussian.md'
    - 'Theano and Lasagne': 'physics/theano_lasagne.md'
    - 'Python Environments': 'physics/python.md'
  - 'Moving your data from Scratch': 'scratch.md'
  - 'GViking': 'gpu.md'
  - 'ADACx (Windows)': 'adacx.md'

    
